apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ0ZWNoc3lzdmJvLmpmcm9nLmlvIjogewoJCQkiYXV0aCI6ICJkR1ZqYUhONWMzWmliMEJuYldGcGJDNWpiMjA2WTIxV2JXUkhkSFZQYWtGNFQycEZNMDFxWnpST2Vtc3hUbFJWTm1Nd1VuTk9hMmg0WTNwU1IxRXdOVEZsYW1jellXdFNjVlJWWTNwYU0yOHlVbXBrVHc9PSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
